import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

const Home: NextPage = () => {
    return (
        <div>
            <Head>
                <title>UN WORK</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="m-16">
                <h1 className="text-lg text-green-400 text-center font-semibolds lg:text-4xl">
                    Next.js / TyepScript / Tailwind CSS / Firebaseで作る県大生用バイト掲示板サービス
                </h1>
            </main>
        </div>
    );
};

export default Home;
